# Generated by Django 3.2.8 on 2021-10-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_category_add_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_image',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
