# Generated by Django 3.2.8 on 2021-10-29 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0002_delete_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='market.category')),
            ],
            options={
                'verbose_name': 'Category',
                'db_table': 'category',
                'unique_together': {('code', 'name')},
            },
        ),
    ]
