# Generated by Django 3.2.8 on 2021-10-29 04:36

from django.db import migrations

from market.models import Category

datasets = [
    # 테스트용으로 일부 데이터만 작성
    ['010000', '패션의류', [
        ['010100', '여성의류'], ['010200', '여성언더웨어/잠옷']
    ]],
    ['020000', '패션잡화', [
        ['020100', '여성신발'], ['020200', '남성신발'],
    ]],
    ['030000', '화장품/미용', [
        ['030100', '스킨케어'], ['030200', '베이스메이크업']
    ]],
    ['040000', '디지털/가전', [
        ['040100', '노트북'], ['040200', '노트북엑세서리']
    ]],
    ['050000', '가구/인테리어', [
        ['050100', '침실가구'], ['050200', '거실가구']
    ]],
    # TODO: 데이터셋 추가
    # ['060000', '출산/육아', [
    #
    # ]],
    # ['070000', '식품', [
    #
    # ]],
    # ['080000', '스포츠/레저', [
    #
    # ]],
    # ['090000', '생활/건강', [
    #
    # ]],
    # ['100000', '여가/생활편의', [
    #
    # ]],
    # ['110000', '면세점', [
    #
    # ]],
    # ['120000', '도서', [
    #
    # ]]
]


def generate_category(apps, schema_editor):
    for data in datasets:
        category = Category.objects.create(code=data[0], name=data[1])
        for sub_data in data[2]:
            Category.objects.create(code=sub_data[0], name=sub_data[1], parent_id=category.code)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0003_category'),
    ]

    operations = [
        migrations.RunPython(generate_category, reverse_code=migrations.RunPython.noop)
    ]

