# Generated by Django 3.2.8 on 2021-11-27 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0004_market_add_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProductNotify',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='market.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_notifications', to='market.product')),
            ],
            options={
                'verbose_name': 'UserProductNotify',
                'unique_together': {('product', 'user')},
            },
        ),
        migrations.CreateModel(
            name='UserNotify',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mall_name', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_read_at', models.DateTimeField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='market.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserNotify',
                'unique_together': {('product', 'user')},
            },
        ),
    ]
