# Generated by Django 3.2.8 on 2021-11-27 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0005_usernotify_userproductnotify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproductnotify',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
